[build]
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

# ===================================================================
# HIGH-VOLUME POSTING SCHEDULE - 17 POSTS PER DAY
# 3 Questions + 5 Tips + 9 Facts = 17 daily posts
# ===================================================================

# 🎯 QUESTIONS - 3 times daily
[[functions]]
  path = "netlify/functions/postQuestion.js"
  schedule = "30 3 * * *"   # 9:00 AM IST

[[functions]]
  path = "netlify/functions/postQuestion.js"
  schedule = "0 8 * * *"    # 1:30 PM IST

[[functions]]
  path = "netlify/functions/postQuestion.js"
  schedule = "30 13 * * *"  # 7:00 PM IST

# 📚 STUDY TIPS - 5 times daily
[[functions]]
  path = "netlify/functions/postTip.js"
  schedule = "0 4 * * *"    # 9:30 AM IST

[[functions]]
  path = "netlify/functions/postTip.js"
  schedule = "30 6 * * *"   # 12:00 PM IST

[[functions]]
  path = "netlify/functions/postTip.js"
  schedule = "0 9 * * *"    # 2:30 PM IST

[[functions]]
  path = "netlify/functions/postTip.js"
  schedule = "30 11 * * *"  # 5:00 PM IST

[[functions]]
  path = "netlify/functions/postTip.js"
  schedule = "0 15 * * *"   # 8:30 PM IST

# 📍 FACTS - 9 times daily
[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "0 3 * * *"    # 8:30 AM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "30 4 * * *"   # 10:00 AM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "0 6 * * *"    # 11:30 AM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "30 7 * * *"   # 1:00 PM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "30 9 * * *"   # 3:00 PM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "0 11 * * *"   # 4:30 PM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "0 13 * * *"   # 6:30 PM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "30 14 * * *"  # 8:00 PM IST

[[functions]]
  path = "netlify/functions/postFact.js"
  schedule = "30 15 * * *"  # 9:00 PM IST

# Global function settings
[functions."*"]
  timeout = 30
  memory = 256
