[build]
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

# ===================================================================
# SIMPLE SCHEDULE - START WITH BASIC POSTING
# 3 posts per day to test the system first
# ===================================================================

[functions.morningQuestion]
  schedule = "30 3 * * *"   # 9:00 AM IST - Morning Question

[functions.afternoonFact]
  schedule = "0 8 * * *"    # 1:30 PM IST - Afternoon Fact

[functions.eveningTip]
  schedule = "30 13 * * *"  # 7:00 PM IST - Evening Tip
