[build]
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

# ===================================================================
# SCALED UP - 9 POSTS PER DAY USING EXISTING FUNCTIONS
# ===================================================================

# Questions - 3 times daily
[functions.postQuestion]
  schedule = "30 3 * * *"   # 9:00 AM IST

# Since Netlify doesn't allow duplicate function names in scheduling,
# we'd need to create simple wrapper functions for multiple times
# OR use this approach with different times:

[functions.postFact]
  schedule = "0 4 * * *"    # 9:30 AM IST - Facts

[functions.postTip]  
  schedule = "30 4 * * *"   # 10:00 AM IST - Tips

# For more posts, you'd create simple wrapper functions that call your main ones
